---

clab_version: "0.68.0"

clab_lab_name: netautoai-lab
clab_workdir: /opt/containerlab/netautoai-lab

clab_allowed_sources:
  - "{{ clab_manager_ip }}/32"

clab_required_images:
  - vrnetlab/cisco_iol:17.12.01
  - vrnetlab/cisco_iol:l2-17.12.01

clab_sysctls:
  fs.inotify.max_user_instances: 4096
  fs.inotify.max_user_watches: 524288
  fs.inotify.max_queued_events: 524288
