all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    manager:
      hosts:
        manager-node:
          ansible_host: netautoai
          ansible_user: debian
    lab:
      hosts:
        lab-node:
          ansible_host: netautoai-lab
          ansible_user: debian
          tailscale_hostname: netautoai-lab
