server {
    listen 8082;
    server_name netautoai;

    location / {
        proxy_pass http://zabbix-web:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
