services:
  netbox: &netbox
    image: docker.io/netboxcommunity/netbox:v4.6-5.0.1
    container_name: netbox
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
    env_file: env/netbox.env
    healthcheck:
      test: curl -f http://localhost:8080/login/ || exit 1
      start_period: 90s
      timeout: 3s
      interval: 15s
    volumes:
      - netbox_media:/opt/netbox/netbox/media:rw
      - netbox_reports:/opt/netbox/netbox/reports:rw
      - netbox_scripts:/opt/netbox/netbox/scripts:rw
    networks:
      - automation_net   # exposed to NGINX, reachable by Infrahub for sync
      - netbox_internal

  netbox-worker:
    <<: *netbox
    container_name: netbox_worker
    depends_on:
      netbox:
        condition: service_healthy
    command:
      - /opt/netbox/venv/bin/python
      - /opt/netbox/netbox/manage.py
      - rqworker
    healthcheck:
      test: ps -aux | grep -v grep | grep -q rqworker || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
    networks:
      - netbox_internal

  postgres:
    image: postgres:16-alpine
    container_name: netbox_postgres
    restart: unless-stopped
    env_file: env/postgres.env
    volumes:
      - netbox_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -q -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - netbox_internal

  redis:
    image: redis:7-alpine
    container_name: netbox_redis
    restart: unless-stopped
    command:
      - sh
      - -c
      - "redis-server --appendonly yes --requirepass $$REDIS_PASSWORD"
    env_file: env/redis.env
    volumes:
      - netbox_redis_data:/data
    healthcheck:
      test: '[ $$(redis-cli --pass "$$REDIS_PASSWORD" ping) = "PONG" ]'
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - netbox_internal

  redis-cache:
    image: redis:7-alpine
    container_name: netbox_redis_cache
    restart: unless-stopped
    command:
      - sh
      - -c
      - "redis-server --requirepass $$REDIS_PASSWORD"
    env_file: env/redis-cache.env
    healthcheck:
      test: '[ $$(redis-cli --pass "$$REDIS_PASSWORD" ping) = "PONG" ]'
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - netbox_internal

volumes:
  netbox_media:
  netbox_reports:
  netbox_scripts:
  netbox_postgres_data:
  netbox_redis_data:

networks:
  automation_net:
    external: true
  netbox_internal:
    internal: true
