---
- name: Deploy service stacks
  hosts: manager-node
  become: true
  tasks:
    - name: Sync stack directories
      ansible.posix.synchronize:
        src: "../stacks/{{ item }}/"
        dest: "{{ stacks_dir }}/{{ item }}/"
        delete: true
      loop: "{{ stack_names }}"

    - name: Deploy compose stacks
      community.docker.docker_compose_v2:
        project_src: "{{ stacks_dir }}/{{ item }}"
        state: present
        pull: missing
      loop: "{{ stack_names }}"
